[Update] Preparations for U10 release
Esri/arcgis-runtime-samples-ios pull request #1029
Opened 2021-01-26 21:25 UTC by yo1995

This PR will update related files for U10 release.

- [x] Root README
    - Update the minimum version
    - Remove `latest` from URL pattern to cope with the new doc site
    - Adjust wordings for CocoaPods
- [ ]

2021-01-26 23:00 UTC, yo1995 commented
The draft release note for U10 tag
---

The following samples have been added:

• Augmented reality > View hidden infrastructure in AR
• Layers > Add ENC exchange set
• Geometry > Buffer list
• Route and directions > Navigate route with rerouting

The following samples have been updated:

• Layers > Edit KML groud overlay
• Layers > Export tiles
• Layers > ArcGIS vector tiled layer (custom style)
• Layers > Group layers
• Layers > Apply mosaic rule to rasters
• Scenes > Add integrated mesh layer
• Augmented reality > Flyover AR
• Scenes > Create terrain from local tile package
• Maps > Change basemap
• Geometry > Spatial operations

In addition, this update includes the following changes:

• Added Dark Mode adaption
• Slightly improved coding style
• Updated build phases and path to the new ArcGIS Framework
• Incorporated API key and new basemap constructors

2021-01-26 23:02 UTC, yo1995 reviewed
Please share your thoughts on the following stuff! 

Once the toolkit is released, I'll update to its latest commit, and merge this PR into `v.next`
Then I'll create the PR to merge `v.next` into `master`, and tag the release.

2021-01-26 23:28 UTC, yo1995 commented
Currently we cannot build a preview sample code documentation site based on `v.next`, as it will need to wait until the site go live. 😕

2021-01-27 01:04 UTC, mikewilburn commented on README.md
> +This repository contains Swift sample code demonstrating the capabilities of [ArcGIS Runtime SDK for iOS](https://developers.arcgis.com/ios/) and how to use them in your own app. The project that can
That's correct. The new links should redirect, but thanks for taking care of this one!

2021-01-27 05:36 UTC, dg0yal requested changes

2021-01-27 05:36 UTC, dg0yal commented on README.md
> +This repository contains Swift sample code demonstrating the capabilities of [ArcGIS Runtime SDK for iOS](https://developers.arcgis.com/ios/) and how to use them in your own app. The project that can
```suggestion
This repository contains Swift sample code demonstrating the capabilities of [ArcGIS Runtime SDK for iOS](https://developers.arcgis.com/ios/) and how to use them in your own app. The project can be opened in Xcode and run on a simulator or a device. Or you can [download the app from the App Store](https://itunes.apple.com/us/app/arcgis-runtime-sdk-for-ios/id1180714771) on your iOS device.
```

2021-01-27 05:36 UTC, dg0yal commented on README.md
> +1. **Select** the `arcgis-ios-sdk-samples` project node, go to the `Build Phases` tab, and **delete** the phases for `Embed Frameworks`. (the phase conflicts with CocoaPods and are only required when
```suggestion
1. **Select** the `arcgis-ios-sdk-samples` project node, go to the `Build Phases` tab, and **delete** the phases for `Embed Frameworks`. (This phase conflicts with CocoaPods and is only required when using the installed SDK as described in the previous section)
```

2021-01-27 05:39 UTC, dg0yal approved these changes

2021-01-27 15:56 UTC, vquach2404 approved these changes

2021-01-27 16:29 UTC, dg0yal commented
Let’s go 
Let’s go

2021-01-27 16:35 UTC, yo1995 commented
I've updated the toolkit to U10!

2021-01-27 16:50 UTC, dg0yal approved these changes

2021-01-27 16:57 UTC, vquach2404 approved these changes

2021-01-27 16:57 UTC, merged