Update bitcode settings
Esri/arcgis-runtime-samples-ios pull request #1197
Opened 2022-08-12 21:27 UTC by vquach2404

This PR addresses the build errors with Xcode 14. See `cocoa/issues/11193` for more info.

2022-08-12 21:50 UTC, yo1995 approved these changes
I'm not fully aware of the impact of this change - seems to be required by Xcode 14. 
But it is the only change we need to make in the project file - that is what I approve here. 😅 

Edit: I also suggest marking this PR as draft, as we are not including it in the upcoming release next week, building with Xcode 13.

Edit again: with the latest change to default setting, we can merge it now.

2022-08-12 21:51 UTC, philium commented
A couple questions:

1. Did you try using the default value (select the setting and press the Delete key)?
2. Did you try uploading a build to App Store Connect after making these changes?

2022-08-12 21:55 UTC, yo1995 requested changes
Pressing delete to go to default value will remove the entries in the project file.

2022-08-12 22:21 UTC, philium commented
> shows like this in Xcode UI

@yo1995 Is that in Xcode 13 or 14? With that change, I'm hoping they'll be different, with Xcode 13 being Yes and Xcode 14 being No.

2022-08-12 22:25 UTC, yo1995 commented
> Is that in Xcode 13 or 14? With that change, I'm hoping they'll be different, with Xcode 13 being Yes and Xcode 14 being No.

That is verified. The screenshot above was Xcode 13. See the comparison below by resetting the bitcode config to default.

|Xcode 13|Xcode 14|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/9660181/184449778-b1012fed-4deb-4812-97c3-f90264c609e6.png)|![image](https://user-images.githubusercontent.com/9660181/184452319-0f846d75-203f-49c0-ace8-81d4b0561b62.png)|

2022-08-12 22:26 UTC, yo1995 commented on arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
> +				ENABLE_BITCODE = NO;
```suggestion
```

2022-08-12 22:26 UTC, yo1995 commented on arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
> +				ENABLE_BITCODE = NO;
```suggestion
```

2022-08-12 22:39 UTC, saratchandrakarumuri submitted a review, later dismissed

2022-08-12 22:42 UTC, vquach2404 commented
> 2. Did you try uploading a build to App Store Connect after making these changes?

To answer your other question, I ran into no errors with bitcode set to "No" (Xcode 13.4) while uploading a build to AppStore Connect.

2022-08-12 22:48 UTC, yo1995 approved these changes

2022-08-16 15:46 UTC, dg0yal commented
> Edit: I also suggest marking this PR as draft, as we are not including it in the upcoming release next week, building with Xcode 13.

This change should not hurt Xcode 13
We should get this into the U15 release so that when users upgrade to xcode 14 in the fall things will continue to work

2022-08-16 17:00 UTC, dg0yal approved these changes

2022-08-16 17:08 UTC, merged