Rename Stretch renderer
Esri/arcgis-runtime-samples-ios pull request #960
Opened 2020-09-04 23:13 UTC by vquach2404

Renamed metadata, files, class, function.

2020-09-04 23:17 UTC, yo1995 approved these changes

2020-09-08 21:37 UTC, philium requested changes

2020-09-08 21:37 UTC, philium commented on arcgis-ios-sdk-samples/Layers/Stretch renderer/StretchRendererViewController.swift
>      // MARK: - StretchRendererSettingsVCDelegate
Please update this to the new name.

2020-09-08 21:37 UTC, philium commented on arcgis-ios-sdk-samples/Layers/Stretch renderer/StretchRendererViewController.swift
> +    func stretchRendererSettingsViewController(_ stretchRendererSettingsVC: StretchRendererSettingsViewController, didSelectStretchParameters parameters: AGSStretchParameters) {
Please update the first parameter name to match the protocol definition.

2020-09-08 23:11 UTC, yo1995 approved these changes

2020-09-09 13:33 UTC, philium approved these changes

2020-09-09 18:43 UTC, merged