Update: remove -j flag from download script and fix portal item
Esri/arcgis-runtime-samples-ios pull request #979
Opened 2020-10-06 23:03 UTC by yo1995

This PR fixes the issue in #857 (Animate images with image overlay) and #865 , where we decided to add "-j" flag to call `unzip` so that it omits all enclosing folders and extract files to a flattened directory. It also replaced the item that caused trouble.

Removing the flag means now extracting zip archive will preserve their folder structure, and we need to

- Add the folder tree as-is when introducing new item to the `Portal Data` folder
- (Negotiate with sample designer to) ensure the zip archive does not contain irrelevant hidden files or redundant folders

2020-10-07 07:36 UTC, philium requested changes

2020-10-07 07:36 UTC, philium commented on arcgis-ios-sdk-samples/Content Display Logic/PortalItems.plist
> +			<string>d1453556d91e46dea191c20c398b82cd</string>
Please update the item identifier in the sample's README.

2020-10-07 16:21 UTC, philium approved these changes

2020-10-07 16:24 UTC, yo1995 commented
@saratchandrakarumuri Please verify `Animate images with image overlay` sample still work as expected. Thanks~

2020-10-09 21:40 UTC, vquach2404 approved these changes
This works fine on my end!

2020-10-09 22:12 UTC, merged